### ISSUE TITLE
how to handle null values in expression 

### ISSUE THREAD

**Issue by meisam94** [mariuszgromada/MathParser.org-mXparser#228]
hi @mariuszgromada 

I have this code:

`        expression1.setExpressionString("mean(add(100, x , 300, 400))");
`
and I found x as missingUserDefinedArguments and added it to arguments.

for example, x is an array like this: **{100, null,300, 400,500}** because we receive this array from the server, and sometimes we haven't any data in that field.

for first time answer is 250
but for the second time is NAN.
how can we handle this error to don't count null in the calculation?

**Comment by mariuszgromada** [comment]
Hi. Null values have to be handled by your software before sending it to mxparser, otherwise mxparser gives null in return (the lib does not know how you want to handle null-s). If you expect null values than just write some code that removes the null value or replaces null value with 0 before invoking mxparser. It depends on your needs and the behaviour you would like to have.
