### ISSUE TITLE
Test failing on v5.0.7 which works on v4.4.2

### ISSUE THREAD

**Issue by jesusmmp** [mariuszgromada/MathParser.org-mXparser#282]
### Issue title:
- Test failing on v5.0.7 which works on v4.4.2

### Issue content:

Hi Mariusz!

I'm testing the last version of Marthparser (v5.0.7) on Sakai and we have a problem with a test.
The operation is: (5e-49) * (6E28)

We have set the epsilon 1.0E-99 and we use the disableUlpRounding before the calculate call.
You can check it here: https://github.com/sakaiproject/sakai/commit/7b96ba3ea21d93100865edceaf7f90ce06327230

On version 4.4.2: Result: 3E-20
On version 5.0.7: Result: 0

Am I missing something?
I've been reading this: https://github.com/mariuszgromada/MathParser.org-mXparser/issues/110, even
I've changed disableUlpRounding to disableAlmostIntRounding but the result is the same: 0.

Please, could you help us with this problem?

Other question: When will be released the new 5.1.0 version?

Thanks!

#### If bug/question:
- MathParser.org-mXparser verssion: v4.4.2 vs v5.0.7
- Framework: JAVA

**Comment by mariuszgromada** [comment]
Hi,
Thanks for your question. In v.5.0 a bug in the canonical rounding has been fixed. In order to solve your issue please switch off all the smart rounding modes :-)

```
mXparser.disableCanonicalRounding();
mXparser.disableUlpRounding();
mXparser.disableAlmostIntRounding();

```

I advice to follow below tutorial
https://mathparser.org/mxparser-tutorial/smart-rounding-settings/

For the v.5.1 - I have everything ready, I believe it will be released in 1-2 weeks for now.

Best regards

**Comment by jesusmmp** [comment]
I've just tested and it works!
Thanks for the quick response!

You are the best :)
