### ISSUE TITLE
User defined arguments ending in e

### ISSUE THREAD

**Issue by squin** [mariuszgromada/MathParser.org-mXparser#313]
I saw old issues #3 and #10 but this seems to happen again. If I enter a calculation string of "Area_of_a_circle" and then extract the arguments I get "Area_of_a_circl". Is there a setting I can use to avoid this?

- MathParser.org-mXparser version: v.5.2.1
- Framework:  .net framework 4.8

**Comment by squin** [comment]
Further to this if I enter "Wheel_Radius" and ask for the arguments the first is "Wh" so it seems that an "e" cannot be used in an argument name.

**Comment by mariuszgromada** [comment]
By default, the so-called implied multiplication mode is on, which tries to interpret and understand where the user wanted to enter the multiplication sign. "e" is a special keyword defined in the parser that refers to the Euler number. As a result, if implied multiplication is enabled, and there are no other arguments defined, the parser will split "Area_of_a_circle" into "Ar*e*a_of_a_circl*e". Please take a look at this:

```
Expression e = new Expression("Area_of_a_circle+3");
double v = e.calculate();
System.out.println(e.getExpressionString() + " = " + e.getCanonicalExpressionString());
System.out.println(e.getErrorMessage());
```

Result
```
Area_of_a_circle+3 = Ar*e*a_of_a_circl*e+3
[Area_of_a_circle+3]: Starting syntax check...
[Area_of_a_circle+3]: Token 'Ar', index 1: Invalid token.
[Area_of_a_circle+3]: Token 'a_of_a_circl', index 5: Invalid token.
[Area_of_a_circle+3]: Errors have been found.
```

This is expected behavior. Please follow the below tutorial section: https://mathparser.org/mxparser-tutorial/implied-multiplication/

To control this you have many different options.

**1. Disabling implied multiplication mode**

```
mXparser.disableImpliedMultiplicationMode();
Expression e = new Expression("Area_of_a_circle+3");
double v = e.calculate();
System.out.println(e.getExpressionString() + " = " + e.getCanonicalExpressionString());
System.out.println(e.getErrorMessage());
```

Result
```
Area_of_a_circle+3 = Area_of_a_circle+3
[Area_of_a_circle+3]: Starting syntax check...
[Area_of_a_circle+3]: Token 'Area_of_a_circle', index 1: Invalid token.
[Area_of_a_circle+3]: Errors have been found.
```

Tutorial: https://mathparser.org/mxparser-tutorial/implied-multiplication/

**2. Defining proper arguments / constants / functions**

Argument a = new Argument("Area_of_a_circle = 3");
Expression e = new Expression("Area_of_a_circle+3", a);
double v = e.calculate();
System.out.println(e.getExpressionString() + " = " + e.getCanonicalExpressionString());
System.out.println(e.getErrorMessage());

Result
```
Area_of_a_circle+3 = Area_of_a_circle+3
[Area_of_a_circle+3]: Starting syntax check...
[Area_of_a_circle+3]: No errors detected.
```

Tutorial:
- https://mathparser.org/mxparser-tutorial/user-defined-arguments/
- https://mathparser.org/mxparser-tutorial/user-defined-constants/
- https://mathparser.org/mxparser-tutorial/user-defined-functions/

**3. Removing special keyword e**

```
mXparser.removeBuiltinTokens("e");
Expression e = new Expression("Area_of_a_circle+3");
double v = e.calculate();
System.out.println(e.getExpressionString() + " = " + e.getCanonicalExpressionString());
System.out.println(e.getErrorMessage());
```

Result
```
Area_of_a_circle+3 = Area_of_a_circle+3
[Area_of_a_circle+3]: Starting syntax check...
[Area_of_a_circle+3]: Token 'Area_of_a_circle', index 1: Invalid token.
[Area_of_a_circle+3]: Errors have been found.
```

Tutorial:
- https://mathparser.org/mxparser-tutorial/built-in-tokens-key-words-manipulation/
- https://mathparser.org/mxparser-tutorial/using-internal-help/


Best regards

**Comment by squin** [comment]
Hi Mariusz,

 

Many thanks for this, a quick fix for my problem. I imagine I am not the only one asking this. I should have read the documentation more fully, so my bad.

 

Have a good one.

 

All the best,

 

Simon

**Comment by mariuszgromada** [comment]
Happy to help :-)
