### ISSUE TITLE
abs bug

### ISSUE THREAD

**Issue by zhangliangcome** [mariuszgromada/MathParser.org-mXparser#316]
### Issue title:
There is a bug when the absolute value expression contains exponential form
For example, the expression: (abs(-101^2+2*101-3)) and the expression (abs(101^2-2*101+3)) should be equivalent, but the returned results are 10400.0 and 10002.0 respectively. abs(-101^2 is processed as a whole and the following expressions

#### If bug/question:
        Expression e=new Expression("(abs(-101^2+2*101-3))");
        System.out.println(e.calculate());
        Expression e1=new Expression("(abs(101^2-2*101+3))");
        System.out.println(e1.calculate());

#### If new feature
- Feature description
- Use case description

**Comment by mariuszgromada** [comment]
Thank you, this is not a bug. I decided to take this action consciously on the user requests. Such an expression is interpreted identically by e.g. MS Excel. Notation like `"-10^2+2"` is messy and incorrect in mathematics, it should not be written this way. The correct notation should use parentheses so that there is no doubt what action is expected. `"-10^2+2"` can be e.g. `"-(10^2)+2"` or `"(-10)^2+2"`. This ambiguity concerns that minus sign at the beginning of the expression. Therefore, the mxparser software interprets `"-10^2+2" as "(-10)^2+2"` because it is a number and the entire expression/subexpression starts with a minus sign. The software will work differently if a symbol/argument is used in this position.

```
Argument a = new Argument("a = 101");
Expression e=new Expression("(abs(-a^2+2*101-3))", a);
System.out.println(e.calculate());
Expression e1=new Expression("(abs(a^2-2*101+3))", a);
System.out.println(e1.calculate());
```

Best regards!

**Comment by zhangliangcome** [comment]
Got it. Thank you for your answer. That’s great.

Best regards!
